##
## Copyright (C) 2010 Thomas Eriksson
##
## This program is free software; you can redistribute it and/or
## modify it under the terms of the GNU General Public License
## as published by the Free Software Foundation; either version 2
## of the License, or (at your option) any later version.
##
## This program is distributed in the hope that it will be useful,
## but WITHOUT ANY WARRANTY; without even the implied warranty of
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
## GNU General Public License for more details.
##
## You should have received a copy of the GNU General Public License
## along with this program; if not, write to the Free Software
## Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
##

## Makefile for the bashish theme engine. Can install bashish, 
## create packages in tar.gz and rpm formats.
##

BASHISH_SHELL := @BASHISH_SHELL@
INSTALL := /usr/bin/install -c

prefix = /home/thioshp
PACKAGE_TARNAME = bashish
exec_prefix = ${prefix}
datarootdir = ${prefix}/share
datadir = ${datarootdir}
bindir = ${exec_prefix}/bin
mandir = ${datarootdir}/man
sysconfdir = ${prefix}/etc
docdir = ${datarootdir}/doc/${PACKAGE_TARNAME}
pkgdatadir = $(datadir)/bashish

##
## Generate file headers for scripts
##

bashish:
	:

## Copy all the source files into a new directory and use tar to create
## an archive from it. Simplest way I could think of to make an archive
## witout backups, autogenerated files, etc.
##
## Uses install instead of mkdir so build won't fail if the directory 
## exists
tar: 	distclean
	rm -f Makefile
	( cd ..;tar cvf bashish-2.2.4.tar bashish-2.2.4 )

tar.gz: tar
	gzip -9 -c ../bashish-2.2.4.tar > ../bashish-2.2.4.tar.gz

rpm:	tar.gz
	cp ../bashish-2.2.4.tar.gz ${HOME}/redhat/SOURCES
	rpmbuild --nodeps -bb bashish.spec

dist:	distclean tar.gz rpm

clean:
	rm -f data/bashish_version data/lib/_bashish_launcher
	rm -f man/*.1

distclean: clean
	rm -f config.log config.status
##
## create bashish directory structure
##
install: bashish install-data install-man install-doc

install-data:
	$(INSTALL) -m 755 -d $(DESTDIR)$(pkgdatadir)/defaults
	$(INSTALL) -m 755 -d $(DESTDIR)$(pkgdatadir)/lib
	$(INSTALL) -m 755 -d $(DESTDIR)$(pkgdatadir)/main
	$(INSTALL) -m 755 -d $(DESTDIR)$(pkgdatadir)/main/bashish
	$(INSTALL) -m 755 -d $(DESTDIR)$(pkgdatadir)/main/bashish/sys
	$(INSTALL) -m 755 -d $(DESTDIR)$(pkgdatadir)/main/prompt
	$(INSTALL) -m 755 -d $(DESTDIR)$(pkgdatadir)/main/prompt/csh
	$(INSTALL) -m 755 -d $(DESTDIR)$(pkgdatadir)/main/prompt/csh/sys
	$(INSTALL) -m 755 -d $(DESTDIR)$(pkgdatadir)/main/prompt/dos
	$(INSTALL) -m 755 -d $(DESTDIR)$(pkgdatadir)/main/prompt/dos/sys
	$(INSTALL) -m 755 -d $(DESTDIR)$(pkgdatadir)/main/prompt/fish
	$(INSTALL) -m 755 -d $(DESTDIR)$(pkgdatadir)/main/prompt/fish/sys
	$(INSTALL) -m 755 -d $(DESTDIR)$(pkgdatadir)/main/prompt/osh
	$(INSTALL) -m 755 -d $(DESTDIR)$(pkgdatadir)/main/prompt/rc
	$(INSTALL) -m 755 -d $(DESTDIR)$(pkgdatadir)/main/prompt/rc/sys
	$(INSTALL) -m 755 -d $(DESTDIR)$(pkgdatadir)/main/prompt/sh
	$(INSTALL) -m 755 -d $(DESTDIR)$(pkgdatadir)/main/terminal
	$(INSTALL) -m 755 -d $(DESTDIR)$(pkgdatadir)/main/terminal/engine
	$(INSTALL) -m 755 -d $(DESTDIR)$(pkgdatadir)/main/terminal/templates
	$(INSTALL) -m 755 -d $(DESTDIR)$(pkgdatadir)/main/terminal/templates/gnome-terminal
	$(INSTALL) -m 755 -d $(DESTDIR)$(pkgdatadir)/overrides
	$(INSTALL) -m 755 -d $(DESTDIR)$(pkgdatadir)/themes
	$(INSTALL) -m 755 -d $(DESTDIR)$(pkgdatadir)/themes/app
	$(INSTALL) -m 755 -d $(DESTDIR)$(pkgdatadir)/themes/app/appchat
	$(INSTALL) -m 755 -d $(DESTDIR)$(pkgdatadir)/themes/app/appcompress
	$(INSTALL) -m 755 -d $(DESTDIR)$(pkgdatadir)/themes/app/appeditor
	$(INSTALL) -m 755 -d $(DESTDIR)$(pkgdatadir)/themes/app/appeditornofont
	$(INSTALL) -m 755 -d $(DESTDIR)$(pkgdatadir)/themes/app/appeditor_reversed
	$(INSTALL) -m 755 -d $(DESTDIR)$(pkgdatadir)/themes/app/appevilroot
	$(INSTALL) -m 755 -d $(DESTDIR)$(pkgdatadir)/themes/app/appgeneric
	$(INSTALL) -m 755 -d $(DESTDIR)$(pkgdatadir)/themes/app/apphearttracker
	$(INSTALL) -m 755 -d $(DESTDIR)$(pkgdatadir)/themes/app/appinvertfgbg
	$(INSTALL) -m 755 -d $(DESTDIR)$(pkgdatadir)/themes/app/appjavac
	$(INSTALL) -m 755 -d $(DESTDIR)$(pkgdatadir)/themes/app/applatex
	$(INSTALL) -m 755 -d $(DESTDIR)$(pkgdatadir)/themes/app/appmanual
	$(INSTALL) -m 755 -d $(DESTDIR)$(pkgdatadir)/themes/app/appmixer
	$(INSTALL) -m 755 -d $(DESTDIR)$(pkgdatadir)/themes/app/appvideo
	$(INSTALL) -m 755 -d $(DESTDIR)$(pkgdatadir)/themes/ascii-art
	$(INSTALL) -m 755 -d $(DESTDIR)$(pkgdatadir)/themes/ascii-art/bashish2
	$(INSTALL) -m 755 -d $(DESTDIR)$(pkgdatadir)/themes/ascii-art/bluesteel
	$(INSTALL) -m 755 -d $(DESTDIR)$(pkgdatadir)/themes/ascii-art/box
	$(INSTALL) -m 755 -d $(DESTDIR)$(pkgdatadir)/themes/ascii-art/conda
	$(INSTALL) -m 755 -d $(DESTDIR)$(pkgdatadir)/themes/ascii-art/elite
	$(INSTALL) -m 755 -d $(DESTDIR)$(pkgdatadir)/themes/ascii-art/elite2
	$(INSTALL) -m 755 -d $(DESTDIR)$(pkgdatadir)/themes/ascii-art/fade
	$(INSTALL) -m 755 -d $(DESTDIR)$(pkgdatadir)/themes/ascii-art/fire
	$(INSTALL) -m 755 -d $(DESTDIR)$(pkgdatadir)/themes/ascii-art/flowerpower
	$(INSTALL) -m 755 -d $(DESTDIR)$(pkgdatadir)/themes/ascii-art/m0an
	$(INSTALL) -m 755 -d $(DESTDIR)$(pkgdatadir)/themes/ascii-art/moo
	$(INSTALL) -m 755 -d $(DESTDIR)$(pkgdatadir)/themes/ascii-art/poker
	$(INSTALL) -m 755 -d $(DESTDIR)$(pkgdatadir)/themes/ascii-art/spiffydeb
	$(INSTALL) -m 755 -d $(DESTDIR)$(pkgdatadir)/themes/ascii-art/spiffyred
	$(INSTALL) -m 755 -d $(DESTDIR)$(pkgdatadir)/themes/ascii-art/uberprompt
	$(INSTALL) -m 755 -d $(DESTDIR)$(pkgdatadir)/themes/ascii-art/urbandawn
	$(INSTALL) -m 755 -d $(DESTDIR)$(pkgdatadir)/themes/computer
	$(INSTALL) -m 755 -d $(DESTDIR)$(pkgdatadir)/themes/computer/appleiie
	$(INSTALL) -m 755 -d $(DESTDIR)$(pkgdatadir)/themes/computer/commodore
	$(INSTALL) -m 755 -d $(DESTDIR)$(pkgdatadir)/themes/computer/commodore/amiga
	$(INSTALL) -m 755 -d $(DESTDIR)$(pkgdatadir)/themes/computer/commodore/amigados
	$(INSTALL) -m 755 -d $(DESTDIR)$(pkgdatadir)/themes/computer/commodore/c128
	$(INSTALL) -m 755 -d $(DESTDIR)$(pkgdatadir)/themes/computer/commodore/c64
	$(INSTALL) -m 755 -d $(DESTDIR)$(pkgdatadir)/themes/computer/commodore/cbmii
	$(INSTALL) -m 755 -d $(DESTDIR)$(pkgdatadir)/themes/computer/commodore/pet
	$(INSTALL) -m 755 -d $(DESTDIR)$(pkgdatadir)/themes/computer/commodore/vic20
	$(INSTALL) -m 755 -d $(DESTDIR)$(pkgdatadir)/themes/computer/dos
	$(INSTALL) -m 755 -d $(DESTDIR)$(pkgdatadir)/themes/computer/lcars
	$(INSTALL) -m 755 -d $(DESTDIR)$(pkgdatadir)/themes/computer/multics
	$(INSTALL) -m 755 -d $(DESTDIR)$(pkgdatadir)/themes/computer/mvs
	$(INSTALL) -m 755 -d $(DESTDIR)$(pkgdatadir)/themes/computer/mvsmono
	$(INSTALL) -m 755 -d $(DESTDIR)$(pkgdatadir)/themes/computer/oric1
	$(INSTALL) -m 755 -d $(DESTDIR)$(pkgdatadir)/themes/computer/ubuntu
	$(INSTALL) -m 644 data/bashish-version $(DESTDIR)$(pkgdatadir)/bashish-version
	$(INSTALL) -m 644 data/defaults/gnome-terminal.png $(DESTDIR)$(pkgdatadir)/defaults/gnome-terminal.png
	$(INSTALL) -m 755 data/defaults/prompt.csh $(DESTDIR)$(pkgdatadir)/defaults/prompt.csh
	$(INSTALL) -m 644 data/defaults/prompt.dos $(DESTDIR)$(pkgdatadir)/defaults/prompt.dos
	$(INSTALL) -m 755 data/defaults/prompt.fish $(DESTDIR)$(pkgdatadir)/defaults/prompt.fish
	$(INSTALL) -m 644 data/defaults/prompt.kiss $(DESTDIR)$(pkgdatadir)/defaults/prompt.kiss
	$(INSTALL) -m 755 data/defaults/prompt.rc $(DESTDIR)$(pkgdatadir)/defaults/prompt.rc
	$(INSTALL) -m 755 data/defaults/prompt.sh $(DESTDIR)$(pkgdatadir)/defaults/prompt.sh
	$(INSTALL) -m 755 data/defaults/prompt.tcsh $(DESTDIR)$(pkgdatadir)/defaults/prompt.tcsh
	$(INSTALL) -m 755 data/defaults/theme $(DESTDIR)$(pkgdatadir)/defaults/theme
	$(INSTALL) -m 755 data/lib/_bashish_bashishtheme_launcher $(DESTDIR)$(pkgdatadir)/lib/_bashish_bashishtheme_launcher
	$(INSTALL) -m 755 data/lib/_bashish_isxterm $(DESTDIR)$(pkgdatadir)/lib/_bashish_isxterm
	$(INSTALL) -m 755 data/lib/_bashish_launcher $(DESTDIR)$(pkgdatadir)/lib/_bashish_launcher
	$(INSTALL) -m 755 data/lib/_bashish_prompt_asciilogo $(DESTDIR)$(pkgdatadir)/lib/_bashish_prompt_asciilogo
	$(INSTALL) -m 755 data/lib/_bashish_prompt_cbmerror $(DESTDIR)$(pkgdatadir)/lib/_bashish_prompt_cbmerror
	$(INSTALL) -m 755 data/lib/_bashish_prompt_cp437 $(DESTDIR)$(pkgdatadir)/lib/_bashish_prompt_cp437
	$(INSTALL) -m 755 data/lib/_bashish_prompt_cwd $(DESTDIR)$(pkgdatadir)/lib/_bashish_prompt_cwd
	$(INSTALL) -m 755 data/lib/_bashish_prompt_fillx $(DESTDIR)$(pkgdatadir)/lib/_bashish_prompt_fillx
	$(INSTALL) -m 755 data/lib/_bashish_prompt_parsecolors $(DESTDIR)$(pkgdatadir)/lib/_bashish_prompt_parsecolors
	$(INSTALL) -m 755 data/lib/_bashish_prompt_rcs $(DESTDIR)$(pkgdatadir)/lib/_bashish_prompt_rcs
	$(INSTALL) -m 755 data/lib/_bashish_prompt_shellvars $(DESTDIR)$(pkgdatadir)/lib/_bashish_prompt_shellvars
	$(INSTALL) -m 755 data/lib/_bashish_prompt_testloc $(DESTDIR)$(pkgdatadir)/lib/_bashish_prompt_testloc
	$(INSTALL) -m 755 data/lib/_bashish_subproc $(DESTDIR)$(pkgdatadir)/lib/_bashish_subproc
	$(INSTALL) -m 755 data/lib/_bashish_utfcheck $(DESTDIR)$(pkgdatadir)/lib/_bashish_utfcheck
	$(INSTALL) -m 755 data/main/bashish/init $(DESTDIR)$(pkgdatadir)/main/bashish/init
	$(INSTALL) -m 755 data/main/bashish/sys/appdb $(DESTDIR)$(pkgdatadir)/main/bashish/sys/appdb
	$(INSTALL) -m 755 data/main/bashish/sys/createdirs $(DESTDIR)$(pkgdatadir)/main/bashish/sys/createdirs
	$(INSTALL) -m 755 data/main/bashish/sys/list $(DESTDIR)$(pkgdatadir)/main/bashish/sys/list
	$(INSTALL) -m 755 data/main/bashish/sys/save $(DESTDIR)$(pkgdatadir)/main/bashish/sys/save
	$(INSTALL) -m 755 data/main/bashish/sys/termcleanup $(DESTDIR)$(pkgdatadir)/main/bashish/sys/termcleanup
	$(INSTALL) -m 755 data/main/bashish/sys/termloader $(DESTDIR)$(pkgdatadir)/main/bashish/sys/termloader
	$(INSTALL) -m 755 data/main/bashish/sys/uninstall $(DESTDIR)$(pkgdatadir)/main/bashish/sys/uninstall
	$(INSTALL) -m 755 data/main/bashish/sys/unpack $(DESTDIR)$(pkgdatadir)/main/bashish/sys/unpack
	$(INSTALL) -m 755 data/main/bashish/sys/update $(DESTDIR)$(pkgdatadir)/main/bashish/sys/update
	$(INSTALL) -m 644 data/main/prompt/csh/autoload $(DESTDIR)$(pkgdatadir)/main/prompt/csh/autoload
	$(INSTALL) -m 755 data/main/prompt/csh/_bashish_module $(DESTDIR)$(pkgdatadir)/main/prompt/csh/_bashish_module
	$(INSTALL) -m 755 data/main/prompt/csh/bashishtheme $(DESTDIR)$(pkgdatadir)/main/prompt/csh/bashishtheme
	$(INSTALL) -m 755 data/main/prompt/csh/init $(DESTDIR)$(pkgdatadir)/main/prompt/csh/init
	$(INSTALL) -m 755 data/main/prompt/csh/sys/detectsh $(DESTDIR)$(pkgdatadir)/main/prompt/csh/sys/detectsh
	$(INSTALL) -m 755 data/main/prompt/csh/sys/loadprompt $(DESTDIR)$(pkgdatadir)/main/prompt/csh/sys/loadprompt
	$(INSTALL) -m 644 data/main/prompt/dos/autoload $(DESTDIR)$(pkgdatadir)/main/prompt/dos/autoload
	$(INSTALL) -m 644 data/main/prompt/dos/init $(DESTDIR)$(pkgdatadir)/main/prompt/dos/init
	$(INSTALL) -m 644 data/main/prompt/dos/sys/ldprompt $(DESTDIR)$(pkgdatadir)/main/prompt/dos/sys/ldprompt
	$(INSTALL) -m 644 data/main/prompt/fish/autoload $(DESTDIR)$(pkgdatadir)/main/prompt/fish/autoload
	$(INSTALL) -m 755 data/main/prompt/fish/init $(DESTDIR)$(pkgdatadir)/main/prompt/fish/init
	$(INSTALL) -m 755 data/main/prompt/fish/sys/loadprompt $(DESTDIR)$(pkgdatadir)/main/prompt/fish/sys/loadprompt
	$(INSTALL) -m 644 data/main/prompt/osh/autoload $(DESTDIR)$(pkgdatadir)/main/prompt/osh/autoload
	$(INSTALL) -m 644 data/main/prompt/rc/autoload $(DESTDIR)$(pkgdatadir)/main/prompt/rc/autoload
	$(INSTALL) -m 755 data/main/prompt/rc/init $(DESTDIR)$(pkgdatadir)/main/prompt/rc/init
	$(INSTALL) -m 755 data/main/prompt/rc/sys/loadprompt $(DESTDIR)$(pkgdatadir)/main/prompt/rc/sys/loadprompt
	$(INSTALL) -m 644 data/main/prompt/sh/autoload $(DESTDIR)$(pkgdatadir)/main/prompt/sh/autoload
	$(INSTALL) -m 755 data/main/prompt/sh/autoload $(DESTDIR)$(pkgdatadir)/main/prompt/sh/autoload
	$(INSTALL) -m 755 data/main/prompt/sh/init $(DESTDIR)$(pkgdatadir)/main/prompt/sh/init
	$(INSTALL) -m 755 data/main/terminal/engine/_bashish_cmdtool_printtitle $(DESTDIR)$(pkgdatadir)/main/terminal/engine/_bashish_cmdtool_printtitle
	$(INSTALL) -m 755 data/main/terminal/engine/_bashish_dtterm_icon $(DESTDIR)$(pkgdatadir)/main/terminal/engine/_bashish_dtterm_icon
	$(INSTALL) -m 755 data/main/terminal/engine/_bashish_dtterm_init $(DESTDIR)$(pkgdatadir)/main/terminal/engine/_bashish_dtterm_init
	$(INSTALL) -m 755 data/main/terminal/engine/_bashish_eterm_ansi $(DESTDIR)$(pkgdatadir)/main/terminal/engine/_bashish_eterm_ansi
	$(INSTALL) -m 755 data/main/terminal/engine/_bashish_eterm_color $(DESTDIR)$(pkgdatadir)/main/terminal/engine/_bashish_eterm_color
	$(INSTALL) -m 755 data/main/terminal/engine/_bashish_eterm_image $(DESTDIR)$(pkgdatadir)/main/terminal/engine/_bashish_eterm_image
	$(INSTALL) -m 755 data/main/terminal/engine/_bashish_generic_bulkprint $(DESTDIR)$(pkgdatadir)/main/terminal/engine/_bashish_generic_bulkprint
	$(INSTALL) -m 755 data/main/terminal/engine/_bashish_generic_cleanvar $(DESTDIR)$(pkgdatadir)/main/terminal/engine/_bashish_generic_cleanvar
	$(INSTALL) -m 755 data/main/terminal/engine/_bashish_generic_winch $(DESTDIR)$(pkgdatadir)/main/terminal/engine/_bashish_generic_winch
	$(INSTALL) -m 755 data/main/terminal/engine/_bashish_gnome-terminal_properties $(DESTDIR)$(pkgdatadir)/main/terminal/engine/_bashish_gnome-terminal_properties
	$(INSTALL) -m 755 data/main/terminal/engine/_bashish_gnome-terminal_winch $(DESTDIR)$(pkgdatadir)/main/terminal/engine/_bashish_gnome-terminal_winch
	$(INSTALL) -m 755 data/main/terminal/engine/_bashish_konsole_init $(DESTDIR)$(pkgdatadir)/main/terminal/engine/_bashish_konsole_init
	$(INSTALL) -m 755 data/main/terminal/engine/_bashish_konsole_properties $(DESTDIR)$(pkgdatadir)/main/terminal/engine/_bashish_konsole_properties
	$(INSTALL) -m 755 data/main/terminal/engine/_bashish_linux_ansi $(DESTDIR)$(pkgdatadir)/main/terminal/engine/_bashish_linux_ansi
	$(INSTALL) -m 755 data/main/terminal/engine/_bashish_linux_color $(DESTDIR)$(pkgdatadir)/main/terminal/engine/_bashish_linux_color
	$(INSTALL) -m 755 data/main/terminal/engine/_bashish_linux_font $(DESTDIR)$(pkgdatadir)/main/terminal/engine/_bashish_linux_font
	$(INSTALL) -m 755 data/main/terminal/engine/_bashish_rxvt_color $(DESTDIR)$(pkgdatadir)/main/terminal/engine/_bashish_rxvt_color
	$(INSTALL) -m 755 data/main/terminal/engine/_bashish_rxvt_image $(DESTDIR)$(pkgdatadir)/main/terminal/engine/_bashish_rxvt_image
	$(INSTALL) -m 755 data/main/terminal/engine/_bashish_urxvt_font $(DESTDIR)$(pkgdatadir)/main/terminal/engine/_bashish_urxvt_font
	$(INSTALL) -m 755 data/main/terminal/engine/_bashish_vt100_posthide $(DESTDIR)$(pkgdatadir)/main/terminal/engine/_bashish_vt100_posthide
	$(INSTALL) -m 755 data/main/terminal/engine/_bashish_vt100_prehide $(DESTDIR)$(pkgdatadir)/main/terminal/engine/_bashish_vt100_prehide
	$(INSTALL) -m 755 data/main/terminal/engine/_bashish_vt100_reverse $(DESTDIR)$(pkgdatadir)/main/terminal/engine/_bashish_vt100_reverse
	$(INSTALL) -m 755 data/main/terminal/engine/_bashish_vt100_sane $(DESTDIR)$(pkgdatadir)/main/terminal/engine/_bashish_vt100_sane
	$(INSTALL) -m 755 data/main/terminal/engine/_bashish_xterm_256 $(DESTDIR)$(pkgdatadir)/main/terminal/engine/_bashish_xterm_256
	$(INSTALL) -m 755 data/main/terminal/engine/_bashish_xterm_ansi $(DESTDIR)$(pkgdatadir)/main/terminal/engine/_bashish_xterm_ansi
	$(INSTALL) -m 755 data/main/terminal/engine/_bashish_xterm_color $(DESTDIR)$(pkgdatadir)/main/terminal/engine/_bashish_xterm_color
	$(INSTALL) -m 755 data/main/terminal/engine/_bashish_xterm_font $(DESTDIR)$(pkgdatadir)/main/terminal/engine/_bashish_xterm_font
	$(INSTALL) -m 755 data/main/terminal/engine/_bashish_xterm_geometry $(DESTDIR)$(pkgdatadir)/main/terminal/engine/_bashish_xterm_geometry
	$(INSTALL) -m 755 data/main/terminal/engine/_bashish_xterm_printtitle $(DESTDIR)$(pkgdatadir)/main/terminal/engine/_bashish_xterm_printtitle
	$(INSTALL) -m 755 data/main/terminal/engine/_bashish_xterm_winch $(DESTDIR)$(pkgdatadir)/main/terminal/engine/_bashish_xterm_winch
	$(INSTALL) -m 755 data/main/terminal/engine/_bashish_xwsh_color $(DESTDIR)$(pkgdatadir)/main/terminal/engine/_bashish_xwsh_color
	$(INSTALL) -m 755 data/main/terminal/init $(DESTDIR)$(pkgdatadir)/main/terminal/init
	$(INSTALL) -m 644 data/main/terminal/templates/gnome-terminal/schema $(DESTDIR)$(pkgdatadir)/main/terminal/templates/gnome-terminal/schema
	$(INSTALL) -m 755 data/overrides/prompt.sh $(DESTDIR)$(pkgdatadir)/overrides/prompt.sh
	$(INSTALL) -m 755 data/overrides/theme $(DESTDIR)$(pkgdatadir)/overrides/theme
	$(INSTALL) -m 644 data/themes/app/appchat/icq.png $(DESTDIR)$(pkgdatadir)/themes/app/appchat/icq.png
	$(INSTALL) -m 644 data/themes/app/appchat/smile.png $(DESTDIR)$(pkgdatadir)/themes/app/appchat/smile.png
	$(INSTALL) -m 755 data/themes/app/appchat/theme $(DESTDIR)$(pkgdatadir)/themes/app/appchat/theme
	$(INSTALL) -m 644 data/themes/app/appcompress/archive.png $(DESTDIR)$(pkgdatadir)/themes/app/appcompress/archive.png
	$(INSTALL) -m 755 data/themes/app/appcompress/theme $(DESTDIR)$(pkgdatadir)/themes/app/appcompress/theme
	$(INSTALL) -m 644 data/themes/app/appeditor/document.png $(DESTDIR)$(pkgdatadir)/themes/app/appeditor/document.png
	$(INSTALL) -m 644 data/themes/app/appeditor/editor.png $(DESTDIR)$(pkgdatadir)/themes/app/appeditor/editor.png
	$(INSTALL) -m 644 data/themes/app/appeditor/gedit.png $(DESTDIR)$(pkgdatadir)/themes/app/appeditor/gedit.png
	$(INSTALL) -m 644 data/themes/app/appeditor/gnu-head.png $(DESTDIR)$(pkgdatadir)/themes/app/appeditor/gnu-head.png
	$(INSTALL) -m 644 data/themes/app/appeditor/nano.png $(DESTDIR)$(pkgdatadir)/themes/app/appeditor/nano.png
	$(INSTALL) -m 755 data/themes/app/appeditor/theme $(DESTDIR)$(pkgdatadir)/themes/app/appeditor/theme
	$(INSTALL) -m 644 data/themes/app/appeditor/vim.png $(DESTDIR)$(pkgdatadir)/themes/app/appeditor/vim.png
	$(INSTALL) -m 644 data/themes/app/appeditornofont/document.png $(DESTDIR)$(pkgdatadir)/themes/app/appeditornofont/document.png
	$(INSTALL) -m 644 data/themes/app/appeditornofont/editor.png $(DESTDIR)$(pkgdatadir)/themes/app/appeditornofont/editor.png
	$(INSTALL) -m 644 data/themes/app/appeditornofont/gedit.png $(DESTDIR)$(pkgdatadir)/themes/app/appeditornofont/gedit.png
	$(INSTALL) -m 644 data/themes/app/appeditornofont/gnu-head.png $(DESTDIR)$(pkgdatadir)/themes/app/appeditornofont/gnu-head.png
	$(INSTALL) -m 644 data/themes/app/appeditornofont/nano.png $(DESTDIR)$(pkgdatadir)/themes/app/appeditornofont/nano.png
	$(INSTALL) -m 755 data/themes/app/appeditornofont/theme $(DESTDIR)$(pkgdatadir)/themes/app/appeditornofont/theme
	$(INSTALL) -m 644 data/themes/app/appeditornofont/vim.png $(DESTDIR)$(pkgdatadir)/themes/app/appeditornofont/vim.png
	$(INSTALL) -m 644 data/themes/app/appeditor_reversed/document.png $(DESTDIR)$(pkgdatadir)/themes/app/appeditor_reversed/document.png
	$(INSTALL) -m 644 data/themes/app/appeditor_reversed/editor.png $(DESTDIR)$(pkgdatadir)/themes/app/appeditor_reversed/editor.png
	$(INSTALL) -m 644 data/themes/app/appeditor_reversed/gedit.png $(DESTDIR)$(pkgdatadir)/themes/app/appeditor_reversed/gedit.png
	$(INSTALL) -m 644 data/themes/app/appeditor_reversed/gnu-head.png $(DESTDIR)$(pkgdatadir)/themes/app/appeditor_reversed/gnu-head.png
	$(INSTALL) -m 644 data/themes/app/appeditor_reversed/nano.png $(DESTDIR)$(pkgdatadir)/themes/app/appeditor_reversed/nano.png
	$(INSTALL) -m 755 data/themes/app/appeditor_reversed/theme $(DESTDIR)$(pkgdatadir)/themes/app/appeditor_reversed/theme
	$(INSTALL) -m 644 data/themes/app/appeditor_reversed/vim.png $(DESTDIR)$(pkgdatadir)/themes/app/appeditor_reversed/vim.png
	$(INSTALL) -m 644 data/themes/app/appevilroot/dialog-warning3.png $(DESTDIR)$(pkgdatadir)/themes/app/appevilroot/dialog-warning3.png
	$(INSTALL) -m 755 data/themes/app/appevilroot/theme $(DESTDIR)$(pkgdatadir)/themes/app/appevilroot/theme
	$(INSTALL) -m 755 data/themes/app/appgeneric/theme $(DESTDIR)$(pkgdatadir)/themes/app/appgeneric/theme
	$(INSTALL) -m 644 data/themes/app/apphearttracker/emblem-mm.png $(DESTDIR)$(pkgdatadir)/themes/app/apphearttracker/emblem-mm.png
	$(INSTALL) -m 644 data/themes/app/apphearttracker/emblem-sound.png $(DESTDIR)$(pkgdatadir)/themes/app/apphearttracker/emblem-sound.png
	$(INSTALL) -m 755 data/themes/app/apphearttracker/theme $(DESTDIR)$(pkgdatadir)/themes/app/apphearttracker/theme
	$(INSTALL) -m 755 data/themes/app/appinvertfgbg/theme $(DESTDIR)$(pkgdatadir)/themes/app/appinvertfgbg/theme
	$(INSTALL) -m 755 data/themes/app/appjavac/theme $(DESTDIR)$(pkgdatadir)/themes/app/appjavac/theme
	$(INSTALL) -m 644 data/themes/app/applatex/tex.png $(DESTDIR)$(pkgdatadir)/themes/app/applatex/tex.png
	$(INSTALL) -m 755 data/themes/app/applatex/theme $(DESTDIR)$(pkgdatadir)/themes/app/applatex/theme
	$(INSTALL) -m 644 data/themes/app/appmanual/book.png $(DESTDIR)$(pkgdatadir)/themes/app/appmanual/book.png
	$(INSTALL) -m 644 data/themes/app/appmanual/man.png $(DESTDIR)$(pkgdatadir)/themes/app/appmanual/man.png
	$(INSTALL) -m 755 data/themes/app/appmanual/theme $(DESTDIR)$(pkgdatadir)/themes/app/appmanual/theme
	$(INSTALL) -m 644 data/themes/app/appmixer/mixer-48.png $(DESTDIR)$(pkgdatadir)/themes/app/appmixer/mixer-48.png
	$(INSTALL) -m 755 data/themes/app/appmixer/theme $(DESTDIR)$(pkgdatadir)/themes/app/appmixer/theme
	$(INSTALL) -m 644 data/themes/app/appmixer/volume.png $(DESTDIR)$(pkgdatadir)/themes/app/appmixer/volume.png
	$(INSTALL) -m 644 data/themes/app/appvideo/emblem-mm.png $(DESTDIR)$(pkgdatadir)/themes/app/appvideo/emblem-mm.png
	$(INSTALL) -m 755 data/themes/app/appvideo/theme $(DESTDIR)$(pkgdatadir)/themes/app/appvideo/theme
	$(INSTALL) -m 644 data/themes/ascii-art/bashish2/logo $(DESTDIR)$(pkgdatadir)/themes/ascii-art/bashish2/logo
	$(INSTALL) -m 755 data/themes/ascii-art/bashish2/prompt.csh $(DESTDIR)$(pkgdatadir)/themes/ascii-art/bashish2/prompt.csh
	$(INSTALL) -m 755 data/themes/ascii-art/bashish2/prompt.rc $(DESTDIR)$(pkgdatadir)/themes/ascii-art/bashish2/prompt.rc
	$(INSTALL) -m 755 data/themes/ascii-art/bashish2/prompt.sh $(DESTDIR)$(pkgdatadir)/themes/ascii-art/bashish2/prompt.sh
	$(INSTALL) -m 755 data/themes/ascii-art/bashish2/prompt.tcsh $(DESTDIR)$(pkgdatadir)/themes/ascii-art/bashish2/prompt.tcsh
	$(INSTALL) -m 755 data/themes/ascii-art/bashish2/theme $(DESTDIR)$(pkgdatadir)/themes/ascii-art/bashish2/theme
	$(INSTALL) -m 644 data/themes/ascii-art/bluesteel/logo $(DESTDIR)$(pkgdatadir)/themes/ascii-art/bluesteel/logo
	$(INSTALL) -m 755 data/themes/ascii-art/bluesteel/prompt.csh $(DESTDIR)$(pkgdatadir)/themes/ascii-art/bluesteel/prompt.csh
	$(INSTALL) -m 755 data/themes/ascii-art/bluesteel/prompt.rc $(DESTDIR)$(pkgdatadir)/themes/ascii-art/bluesteel/prompt.rc
	$(INSTALL) -m 755 data/themes/ascii-art/bluesteel/prompt.sh $(DESTDIR)$(pkgdatadir)/themes/ascii-art/bluesteel/prompt.sh
	$(INSTALL) -m 755 data/themes/ascii-art/bluesteel/prompt.tcsh $(DESTDIR)$(pkgdatadir)/themes/ascii-art/bluesteel/prompt.tcsh
	$(INSTALL) -m 755 data/themes/ascii-art/bluesteel/theme $(DESTDIR)$(pkgdatadir)/themes/ascii-art/bluesteel/theme
	$(INSTALL) -m 755 data/themes/ascii-art/box/prompt.sh $(DESTDIR)$(pkgdatadir)/themes/ascii-art/box/prompt.sh
	$(INSTALL) -m 755 data/themes/ascii-art/box/theme $(DESTDIR)$(pkgdatadir)/themes/ascii-art/box/theme
	$(INSTALL) -m 755 data/themes/ascii-art/conda/prompt.sh $(DESTDIR)$(pkgdatadir)/themes/ascii-art/conda/prompt.sh
	$(INSTALL) -m 755 data/themes/ascii-art/conda/theme $(DESTDIR)$(pkgdatadir)/themes/ascii-art/conda/theme
	$(INSTALL) -m 755 data/themes/ascii-art/elite/prompt.sh $(DESTDIR)$(pkgdatadir)/themes/ascii-art/elite/prompt.sh
	$(INSTALL) -m 755 data/themes/ascii-art/elite/theme $(DESTDIR)$(pkgdatadir)/themes/ascii-art/elite/theme
	$(INSTALL) -m 755 data/themes/ascii-art/elite2/prompt.sh $(DESTDIR)$(pkgdatadir)/themes/ascii-art/elite2/prompt.sh
	$(INSTALL) -m 755 data/themes/ascii-art/elite2/theme $(DESTDIR)$(pkgdatadir)/themes/ascii-art/elite2/theme
	$(INSTALL) -m 755 data/themes/ascii-art/fade/prompt.csh $(DESTDIR)$(pkgdatadir)/themes/ascii-art/fade/prompt.csh
	$(INSTALL) -m 755 data/themes/ascii-art/fade/prompt.sh $(DESTDIR)$(pkgdatadir)/themes/ascii-art/fade/prompt.sh
	$(INSTALL) -m 755 data/themes/ascii-art/fade/prompt.tcsh $(DESTDIR)$(pkgdatadir)/themes/ascii-art/fade/prompt.tcsh
	$(INSTALL) -m 755 data/themes/ascii-art/fade/theme $(DESTDIR)$(pkgdatadir)/themes/ascii-art/fade/theme
	$(INSTALL) -m 755 data/themes/ascii-art/fire/prompt.csh $(DESTDIR)$(pkgdatadir)/themes/ascii-art/fire/prompt.csh
	$(INSTALL) -m 644 data/themes/ascii-art/fire/prompt.dos $(DESTDIR)$(pkgdatadir)/themes/ascii-art/fire/prompt.dos
	$(INSTALL) -m 644 data/themes/ascii-art/fire/prompt.fish $(DESTDIR)$(pkgdatadir)/themes/ascii-art/fire/prompt.fish
	$(INSTALL) -m 755 data/themes/ascii-art/fire/prompt.rc $(DESTDIR)$(pkgdatadir)/themes/ascii-art/fire/prompt.rc
	$(INSTALL) -m 755 data/themes/ascii-art/fire/prompt.sh $(DESTDIR)$(pkgdatadir)/themes/ascii-art/fire/prompt.sh
	$(INSTALL) -m 755 data/themes/ascii-art/fire/prompt.tcsh $(DESTDIR)$(pkgdatadir)/themes/ascii-art/fire/prompt.tcsh
	$(INSTALL) -m 755 data/themes/ascii-art/fire/theme $(DESTDIR)$(pkgdatadir)/themes/ascii-art/fire/theme
	$(INSTALL) -m 755 data/themes/ascii-art/flowerpower/prompt.sh $(DESTDIR)$(pkgdatadir)/themes/ascii-art/flowerpower/prompt.sh
	$(INSTALL) -m 755 data/themes/ascii-art/flowerpower/theme $(DESTDIR)$(pkgdatadir)/themes/ascii-art/flowerpower/theme
	$(INSTALL) -m 755 data/themes/ascii-art/m0an/prompt.bash $(DESTDIR)$(pkgdatadir)/themes/ascii-art/m0an/prompt.bash
	$(INSTALL) -m 755 data/themes/ascii-art/m0an/prompt.tcsh $(DESTDIR)$(pkgdatadir)/themes/ascii-art/m0an/prompt.tcsh
	$(INSTALL) -m 755 data/themes/ascii-art/m0an/theme $(DESTDIR)$(pkgdatadir)/themes/ascii-art/m0an/theme
	$(INSTALL) -m 644 data/themes/ascii-art/m0an/uglyascii $(DESTDIR)$(pkgdatadir)/themes/ascii-art/m0an/uglyascii
	$(INSTALL) -m 644 data/themes/ascii-art/m0an/uglyascii.UTF-8 $(DESTDIR)$(pkgdatadir)/themes/ascii-art/m0an/uglyascii.UTF-8
	$(INSTALL) -m 644 data/themes/ascii-art/m0an/utglyascii.UTF-8 $(DESTDIR)$(pkgdatadir)/themes/ascii-art/m0an/utglyascii.UTF-8
	$(INSTALL) -m 755 data/themes/ascii-art/moo/prompt.bash $(DESTDIR)$(pkgdatadir)/themes/ascii-art/moo/prompt.bash
	$(INSTALL) -m 755 data/themes/ascii-art/moo/theme $(DESTDIR)$(pkgdatadir)/themes/ascii-art/moo/theme
	$(INSTALL) -m 644 data/themes/ascii-art/poker/ambience.xpm $(DESTDIR)$(pkgdatadir)/themes/ascii-art/poker/ambience.xpm
	$(INSTALL) -m 755 data/themes/ascii-art/poker/prompt.bash $(DESTDIR)$(pkgdatadir)/themes/ascii-art/poker/prompt.bash
	$(INSTALL) -m 755 data/themes/ascii-art/poker/theme $(DESTDIR)$(pkgdatadir)/themes/ascii-art/poker/theme
	$(INSTALL) -m 755 data/themes/ascii-art/spiffydeb/prompt.sh $(DESTDIR)$(pkgdatadir)/themes/ascii-art/spiffydeb/prompt.sh
	$(INSTALL) -m 755 data/themes/ascii-art/spiffydeb/theme $(DESTDIR)$(pkgdatadir)/themes/ascii-art/spiffydeb/theme
	$(INSTALL) -m 755 data/themes/ascii-art/spiffyred/prompt.sh $(DESTDIR)$(pkgdatadir)/themes/ascii-art/spiffyred/prompt.sh
	$(INSTALL) -m 755 data/themes/ascii-art/spiffyred/theme $(DESTDIR)$(pkgdatadir)/themes/ascii-art/spiffyred/theme
	$(INSTALL) -m 755 data/themes/ascii-art/uberprompt/prompt.sh $(DESTDIR)$(pkgdatadir)/themes/ascii-art/uberprompt/prompt.sh
	$(INSTALL) -m 755 data/themes/ascii-art/uberprompt/theme $(DESTDIR)$(pkgdatadir)/themes/ascii-art/uberprompt/theme
	$(INSTALL) -m 755 data/themes/ascii-art/urbandawn/prompt.bash $(DESTDIR)$(pkgdatadir)/themes/ascii-art/urbandawn/prompt.bash
	$(INSTALL) -m 755 data/themes/ascii-art/urbandawn/theme $(DESTDIR)$(pkgdatadir)/themes/ascii-art/urbandawn/theme
	$(INSTALL) -m 644 data/themes/computer/appleiie/appleiie $(DESTDIR)$(pkgdatadir)/themes/computer/appleiie/appleiie
	$(INSTALL) -m 755 data/themes/computer/appleiie/prompt.bash $(DESTDIR)$(pkgdatadir)/themes/computer/appleiie/prompt.bash
	$(INSTALL) -m 755 data/themes/computer/appleiie/theme $(DESTDIR)$(pkgdatadir)/themes/computer/appleiie/theme
	$(INSTALL) -m 755 data/themes/computer/commodore/amiga/prompt.bash $(DESTDIR)$(pkgdatadir)/themes/computer/commodore/amiga/prompt.bash
	$(INSTALL) -m 644 data/themes/computer/commodore/amiga/shell.png $(DESTDIR)$(pkgdatadir)/themes/computer/commodore/amiga/shell.png
	$(INSTALL) -m 755 data/themes/computer/commodore/amiga/theme $(DESTDIR)$(pkgdatadir)/themes/computer/commodore/amiga/theme
	$(INSTALL) -m 644 data/themes/computer/commodore/amigados/amiga.png $(DESTDIR)$(pkgdatadir)/themes/computer/commodore/amigados/amiga.png
	$(INSTALL) -m 644 data/themes/computer/commodore/amigados/logo.guru $(DESTDIR)$(pkgdatadir)/themes/computer/commodore/amigados/logo.guru
	$(INSTALL) -m 644 data/themes/computer/commodore/amigados/logo.start $(DESTDIR)$(pkgdatadir)/themes/computer/commodore/amigados/logo.start
	$(INSTALL) -m 755 data/themes/computer/commodore/amigados/prompt.bash $(DESTDIR)$(pkgdatadir)/themes/computer/commodore/amigados/prompt.bash
	$(INSTALL) -m 644 data/themes/computer/commodore/amigados/shell.png $(DESTDIR)$(pkgdatadir)/themes/computer/commodore/amigados/shell.png
	$(INSTALL) -m 755 data/themes/computer/commodore/amigados/theme $(DESTDIR)$(pkgdatadir)/themes/computer/commodore/amigados/theme
	$(INSTALL) -m 644 data/themes/computer/commodore/c128/boot $(DESTDIR)$(pkgdatadir)/themes/computer/commodore/c128/boot
	$(INSTALL) -m 644 data/themes/computer/commodore/c128/commodore.png $(DESTDIR)$(pkgdatadir)/themes/computer/commodore/c128/commodore.png
	$(INSTALL) -m 755 data/themes/computer/commodore/c128/prompt.bash $(DESTDIR)$(pkgdatadir)/themes/computer/commodore/c128/prompt.bash
	$(INSTALL) -m 755 data/themes/computer/commodore/c128/prompt.csh $(DESTDIR)$(pkgdatadir)/themes/computer/commodore/c128/prompt.csh
	$(INSTALL) -m 644 data/themes/computer/commodore/c128/prompt.fish $(DESTDIR)$(pkgdatadir)/themes/computer/commodore/c128/prompt.fish
	$(INSTALL) -m 755 data/themes/computer/commodore/c128/prompt.rc $(DESTDIR)$(pkgdatadir)/themes/computer/commodore/c128/prompt.rc
	$(INSTALL) -m 755 data/themes/computer/commodore/c128/prompt.tcsh $(DESTDIR)$(pkgdatadir)/themes/computer/commodore/c128/prompt.tcsh
	$(INSTALL) -m 755 data/themes/computer/commodore/c128/theme $(DESTDIR)$(pkgdatadir)/themes/computer/commodore/c128/theme
	$(INSTALL) -m 644 data/themes/computer/commodore/c64/boot $(DESTDIR)$(pkgdatadir)/themes/computer/commodore/c64/boot
	$(INSTALL) -m 644 data/themes/computer/commodore/c64/commodore.png $(DESTDIR)$(pkgdatadir)/themes/computer/commodore/c64/commodore.png
	$(INSTALL) -m 755 data/themes/computer/commodore/c64/prompt.bash $(DESTDIR)$(pkgdatadir)/themes/computer/commodore/c64/prompt.bash
	$(INSTALL) -m 755 data/themes/computer/commodore/c64/prompt.csh $(DESTDIR)$(pkgdatadir)/themes/computer/commodore/c64/prompt.csh
	$(INSTALL) -m 644 data/themes/computer/commodore/c64/prompt.fish $(DESTDIR)$(pkgdatadir)/themes/computer/commodore/c64/prompt.fish
	$(INSTALL) -m 755 data/themes/computer/commodore/c64/prompt.rc $(DESTDIR)$(pkgdatadir)/themes/computer/commodore/c64/prompt.rc
	$(INSTALL) -m 755 data/themes/computer/commodore/c64/prompt.tcsh $(DESTDIR)$(pkgdatadir)/themes/computer/commodore/c64/prompt.tcsh
	$(INSTALL) -m 755 data/themes/computer/commodore/c64/theme $(DESTDIR)$(pkgdatadir)/themes/computer/commodore/c64/theme
	$(INSTALL) -m 644 data/themes/computer/commodore/cbmii/boot $(DESTDIR)$(pkgdatadir)/themes/computer/commodore/cbmii/boot
	$(INSTALL) -m 755 data/themes/computer/commodore/cbmii/prompt.bash $(DESTDIR)$(pkgdatadir)/themes/computer/commodore/cbmii/prompt.bash
	$(INSTALL) -m 755 data/themes/computer/commodore/cbmii/theme $(DESTDIR)$(pkgdatadir)/themes/computer/commodore/cbmii/theme
	$(INSTALL) -m 644 data/themes/computer/commodore/pet/boot $(DESTDIR)$(pkgdatadir)/themes/computer/commodore/pet/boot
	$(INSTALL) -m 755 data/themes/computer/commodore/pet/prompt.bash $(DESTDIR)$(pkgdatadir)/themes/computer/commodore/pet/prompt.bash
	$(INSTALL) -m 755 data/themes/computer/commodore/pet/theme $(DESTDIR)$(pkgdatadir)/themes/computer/commodore/pet/theme
	$(INSTALL) -m 644 data/themes/computer/commodore/vic20/boot.32k $(DESTDIR)$(pkgdatadir)/themes/computer/commodore/vic20/boot.32k
	$(INSTALL) -m 644 data/themes/computer/commodore/vic20/boot.5k $(DESTDIR)$(pkgdatadir)/themes/computer/commodore/vic20/boot.5k
	$(INSTALL) -m 644 data/themes/computer/commodore/vic20/commodore.png $(DESTDIR)$(pkgdatadir)/themes/computer/commodore/vic20/commodore.png
	$(INSTALL) -m 755 data/themes/computer/commodore/vic20/prompt.bash $(DESTDIR)$(pkgdatadir)/themes/computer/commodore/vic20/prompt.bash
	$(INSTALL) -m 755 data/themes/computer/commodore/vic20/prompt.csh $(DESTDIR)$(pkgdatadir)/themes/computer/commodore/vic20/prompt.csh
	$(INSTALL) -m 644 data/themes/computer/commodore/vic20/prompt.fish $(DESTDIR)$(pkgdatadir)/themes/computer/commodore/vic20/prompt.fish
	$(INSTALL) -m 755 data/themes/computer/commodore/vic20/prompt.rc $(DESTDIR)$(pkgdatadir)/themes/computer/commodore/vic20/prompt.rc
	$(INSTALL) -m 755 data/themes/computer/commodore/vic20/prompt.tcsh $(DESTDIR)$(pkgdatadir)/themes/computer/commodore/vic20/prompt.tcsh
	$(INSTALL) -m 755 data/themes/computer/commodore/vic20/theme $(DESTDIR)$(pkgdatadir)/themes/computer/commodore/vic20/theme
	$(INSTALL) -m 644 data/themes/computer/commodore/vic20/vic20 $(DESTDIR)$(pkgdatadir)/themes/computer/commodore/vic20/vic20
	$(INSTALL) -m 644 data/themes/computer/commodore/vic20/vic20_startup_screen.gif $(DESTDIR)$(pkgdatadir)/themes/computer/commodore/vic20/vic20_startup_screen.gif
	$(INSTALL) -m 644 data/themes/computer/dos/3270pclogo $(DESTDIR)$(pkgdatadir)/themes/computer/dos/3270pclogo
	$(INSTALL) -m 644 data/themes/computer/dos/8striper $(DESTDIR)$(pkgdatadir)/themes/computer/dos/8striper
	$(INSTALL) -m 644 data/themes/computer/dos/doscopyright $(DESTDIR)$(pkgdatadir)/themes/computer/dos/doscopyright
	$(INSTALL) -m 644 data/themes/computer/dos/msadvlogo $(DESTDIR)$(pkgdatadir)/themes/computer/dos/msadvlogo
	$(INSTALL) -m 755 data/themes/computer/dos/prompt.csh $(DESTDIR)$(pkgdatadir)/themes/computer/dos/prompt.csh
	$(INSTALL) -m 644 data/themes/computer/dos/prompt.dos $(DESTDIR)$(pkgdatadir)/themes/computer/dos/prompt.dos
	$(INSTALL) -m 644 data/themes/computer/dos/prompt.fish $(DESTDIR)$(pkgdatadir)/themes/computer/dos/prompt.fish
	$(INSTALL) -m 755 data/themes/computer/dos/prompt.ksh $(DESTDIR)$(pkgdatadir)/themes/computer/dos/prompt.ksh
	$(INSTALL) -m 755 data/themes/computer/dos/prompt.rc $(DESTDIR)$(pkgdatadir)/themes/computer/dos/prompt.rc
	$(INSTALL) -m 755 data/themes/computer/dos/prompt.sh $(DESTDIR)$(pkgdatadir)/themes/computer/dos/prompt.sh
	$(INSTALL) -m 755 data/themes/computer/dos/prompt.tcsh $(DESTDIR)$(pkgdatadir)/themes/computer/dos/prompt.tcsh
	$(INSTALL) -m 755 data/themes/computer/dos/theme $(DESTDIR)$(pkgdatadir)/themes/computer/dos/theme
	$(INSTALL) -m 644 data/themes/computer/lcars/lcars-2.jpg $(DESTDIR)$(pkgdatadir)/themes/computer/lcars/lcars-2.jpg
	$(INSTALL) -m 755 data/themes/computer/lcars/prompt.csh $(DESTDIR)$(pkgdatadir)/themes/computer/lcars/prompt.csh
	$(INSTALL) -m 755 data/themes/computer/lcars/prompt.sh $(DESTDIR)$(pkgdatadir)/themes/computer/lcars/prompt.sh
	$(INSTALL) -m 755 data/themes/computer/lcars/prompt.tcsh $(DESTDIR)$(pkgdatadir)/themes/computer/lcars/prompt.tcsh
	$(INSTALL) -m 755 data/themes/computer/lcars/theme $(DESTDIR)$(pkgdatadir)/themes/computer/lcars/theme
	$(INSTALL) -m 644 data/themes/computer/multics/boot $(DESTDIR)$(pkgdatadir)/themes/computer/multics/boot
	$(INSTALL) -m 644 data/themes/computer/multics/multics $(DESTDIR)$(pkgdatadir)/themes/computer/multics/multics
	$(INSTALL) -m 755 data/themes/computer/multics/prompt.bash $(DESTDIR)$(pkgdatadir)/themes/computer/multics/prompt.bash
	$(INSTALL) -m 755 data/themes/computer/multics/theme $(DESTDIR)$(pkgdatadir)/themes/computer/multics/theme
	$(INSTALL) -m 644 data/themes/computer/mvs/boot $(DESTDIR)$(pkgdatadir)/themes/computer/mvs/boot
	$(INSTALL) -m 755 data/themes/computer/mvs/prompt.bash $(DESTDIR)$(pkgdatadir)/themes/computer/mvs/prompt.bash
	$(INSTALL) -m 755 data/themes/computer/mvs/theme $(DESTDIR)$(pkgdatadir)/themes/computer/mvs/theme
	$(INSTALL) -m 644 data/themes/computer/mvsmono/boot $(DESTDIR)$(pkgdatadir)/themes/computer/mvsmono/boot
	$(INSTALL) -m 755 data/themes/computer/mvsmono/prompt.bash $(DESTDIR)$(pkgdatadir)/themes/computer/mvsmono/prompt.bash
	$(INSTALL) -m 755 data/themes/computer/mvsmono/theme $(DESTDIR)$(pkgdatadir)/themes/computer/mvsmono/theme
	$(INSTALL) -m 644 data/themes/computer/oric1/boot $(DESTDIR)$(pkgdatadir)/themes/computer/oric1/boot
	$(INSTALL) -m 644 data/themes/computer/oric1/commodore.png $(DESTDIR)$(pkgdatadir)/themes/computer/oric1/commodore.png
	$(INSTALL) -m 755 data/themes/computer/oric1/prompt.bash $(DESTDIR)$(pkgdatadir)/themes/computer/oric1/prompt.bash
	$(INSTALL) -m 755 data/themes/computer/oric1/prompt.csh $(DESTDIR)$(pkgdatadir)/themes/computer/oric1/prompt.csh
	$(INSTALL) -m 644 data/themes/computer/oric1/prompt.fish $(DESTDIR)$(pkgdatadir)/themes/computer/oric1/prompt.fish
	$(INSTALL) -m 755 data/themes/computer/oric1/prompt.rc $(DESTDIR)$(pkgdatadir)/themes/computer/oric1/prompt.rc
	$(INSTALL) -m 755 data/themes/computer/oric1/prompt.tcsh $(DESTDIR)$(pkgdatadir)/themes/computer/oric1/prompt.tcsh
	$(INSTALL) -m 755 data/themes/computer/oric1/theme $(DESTDIR)$(pkgdatadir)/themes/computer/oric1/theme
	$(INSTALL) -m 755 data/themes/computer/ubuntu/prompt.bash $(DESTDIR)$(pkgdatadir)/themes/computer/ubuntu/prompt.bash
	$(INSTALL) -m 755 data/themes/computer/ubuntu/prompt.tcsh $(DESTDIR)$(pkgdatadir)/themes/computer/ubuntu/prompt.tcsh
	$(INSTALL) -m 755 data/themes/computer/ubuntu/theme $(DESTDIR)$(pkgdatadir)/themes/computer/ubuntu/theme
	$(INSTALL) -m 755 -d $(DESTDIR)$(bindir)
	$(INSTALL) -m 755 bin/bashish $(DESTDIR)$(bindir)/bashish
	$(INSTALL) -m 755 bin/bashish $(DESTDIR)$(bindir)/bashish
	$(INSTALL) -m 755 bin/bashishtheme $(DESTDIR)$(bindir)/bashishtheme

install-doc:
	$(INSTALL) -m 755 -d $(DESTDIR)$(docdir)
	$(INSTALL) -m 644 README $(DESTDIR)$(docdir)/README
	$(INSTALL) -m 644 ChangeLog $(DESTDIR)$(docdir)/ChangeLog
	$(INSTALL) -m 644 TODO $(DESTDIR)$(docdir)/TODO
	$(INSTALL) -m 644 CREDITS $(DESTDIR)$(docdir)/CREDITS
	$(INSTALL) -m 644 BUGS $(DESTDIR)$(docdir)/BUGS
	$(INSTALL) -m 644 HACKING $(DESTDIR)$(docdir)/HACKING
	$(INSTALL) -m 644 THEME $(DESTDIR)$(docdir)/THEME

install-man: bashish
	$(INSTALL) -m 755 -d $(DESTDIR)$(mandir)
	$(INSTALL) -m 755 -d $(DESTDIR)$(mandir)/man1
	$(INSTALL) -m 644 man/bashish.1 $(DESTDIR)$(mandir)/man1/bashish.1
	$(INSTALL) -m 644 man/bashish.1 $(DESTDIR)$(mandir)/man1/bashish.1
##
## uninstall files
##
uninstall:
	rm -r $(DESTDIR)$(docdir)
	rm -f $(DESTDIR)$(mandir)/man1/bashish.1
	rm -f $(DESTDIR)$(mandir)/man1/bashish.1
	rm -f $(DESTDIR)$(pkgdatadir)/bashish-version
	rm -f $(DESTDIR)$(pkgdatadir)/defaults/gnome-terminal.png
	rm -f $(DESTDIR)$(pkgdatadir)/defaults/prompt.csh
	rm -f $(DESTDIR)$(pkgdatadir)/defaults/prompt.dos
	rm -f $(DESTDIR)$(pkgdatadir)/defaults/prompt.fish
	rm -f $(DESTDIR)$(pkgdatadir)/defaults/prompt.kiss
	rm -f $(DESTDIR)$(pkgdatadir)/defaults/prompt.rc
	rm -f $(DESTDIR)$(pkgdatadir)/defaults/prompt.sh
	rm -f $(DESTDIR)$(pkgdatadir)/defaults/prompt.tcsh
	rm -f $(DESTDIR)$(pkgdatadir)/defaults/theme
	rm -f $(DESTDIR)$(pkgdatadir)/lib/_bashish_bashishtheme_launcher
	rm -f $(DESTDIR)$(pkgdatadir)/lib/_bashish_isxterm
	rm -f $(DESTDIR)$(pkgdatadir)/lib/_bashish_launcher
	rm -f $(DESTDIR)$(pkgdatadir)/lib/_bashish_prompt_asciilogo
	rm -f $(DESTDIR)$(pkgdatadir)/lib/_bashish_prompt_cbmerror
	rm -f $(DESTDIR)$(pkgdatadir)/lib/_bashish_prompt_cp437
	rm -f $(DESTDIR)$(pkgdatadir)/lib/_bashish_prompt_cwd
	rm -f $(DESTDIR)$(pkgdatadir)/lib/_bashish_prompt_fillx
	rm -f $(DESTDIR)$(pkgdatadir)/lib/_bashish_prompt_parsecolors
	rm -f $(DESTDIR)$(pkgdatadir)/lib/_bashish_prompt_rcs
	rm -f $(DESTDIR)$(pkgdatadir)/lib/_bashish_prompt_shellvars
	rm -f $(DESTDIR)$(pkgdatadir)/lib/_bashish_prompt_testloc
	rm -f $(DESTDIR)$(pkgdatadir)/lib/_bashish_subproc
	rm -f $(DESTDIR)$(pkgdatadir)/lib/_bashish_utfcheck
	rm -f $(DESTDIR)$(pkgdatadir)/main/bashish/init
	rm -f $(DESTDIR)$(pkgdatadir)/main/bashish/sys/appdb
	rm -f $(DESTDIR)$(pkgdatadir)/main/bashish/sys/createdirs
	rm -f $(DESTDIR)$(pkgdatadir)/main/bashish/sys/list
	rm -f $(DESTDIR)$(pkgdatadir)/main/bashish/sys/save
	rm -f $(DESTDIR)$(pkgdatadir)/main/bashish/sys/termcleanup
	rm -f $(DESTDIR)$(pkgdatadir)/main/bashish/sys/termloader
	rm -f $(DESTDIR)$(pkgdatadir)/main/bashish/sys/uninstall
	rm -f $(DESTDIR)$(pkgdatadir)/main/bashish/sys/unpack
	rm -f $(DESTDIR)$(pkgdatadir)/main/bashish/sys/update
	rm -f $(DESTDIR)$(pkgdatadir)/main/prompt/csh/autoload
	rm -f $(DESTDIR)$(pkgdatadir)/main/prompt/csh/_bashish_module
	rm -f $(DESTDIR)$(pkgdatadir)/main/prompt/csh/bashishtheme
	rm -f $(DESTDIR)$(pkgdatadir)/main/prompt/csh/init
	rm -f $(DESTDIR)$(pkgdatadir)/main/prompt/csh/sys/detectsh
	rm -f $(DESTDIR)$(pkgdatadir)/main/prompt/csh/sys/loadprompt
	rm -f $(DESTDIR)$(pkgdatadir)/main/prompt/dos/autoload
	rm -f $(DESTDIR)$(pkgdatadir)/main/prompt/dos/init
	rm -f $(DESTDIR)$(pkgdatadir)/main/prompt/dos/sys/ldprompt
	rm -f $(DESTDIR)$(pkgdatadir)/main/prompt/fish/autoload
	rm -f $(DESTDIR)$(pkgdatadir)/main/prompt/fish/init
	rm -f $(DESTDIR)$(pkgdatadir)/main/prompt/fish/sys/loadprompt
	rm -f $(DESTDIR)$(pkgdatadir)/main/prompt/osh/autoload
	rm -f $(DESTDIR)$(pkgdatadir)/main/prompt/rc/autoload
	rm -f $(DESTDIR)$(pkgdatadir)/main/prompt/rc/init
	rm -f $(DESTDIR)$(pkgdatadir)/main/prompt/rc/sys/loadprompt
	rm -f $(DESTDIR)$(pkgdatadir)/main/prompt/sh/autoload
	rm -f $(DESTDIR)$(pkgdatadir)/main/prompt/sh/autoload
	rm -f $(DESTDIR)$(pkgdatadir)/main/prompt/sh/init
	rm -f $(DESTDIR)$(pkgdatadir)/main/terminal/engine/_bashish_cmdtool_printtitle
	rm -f $(DESTDIR)$(pkgdatadir)/main/terminal/engine/_bashish_dtterm_icon
	rm -f $(DESTDIR)$(pkgdatadir)/main/terminal/engine/_bashish_dtterm_init
	rm -f $(DESTDIR)$(pkgdatadir)/main/terminal/engine/_bashish_eterm_ansi
	rm -f $(DESTDIR)$(pkgdatadir)/main/terminal/engine/_bashish_eterm_color
	rm -f $(DESTDIR)$(pkgdatadir)/main/terminal/engine/_bashish_eterm_image
	rm -f $(DESTDIR)$(pkgdatadir)/main/terminal/engine/_bashish_generic_bulkprint
	rm -f $(DESTDIR)$(pkgdatadir)/main/terminal/engine/_bashish_generic_cleanvar
	rm -f $(DESTDIR)$(pkgdatadir)/main/terminal/engine/_bashish_generic_winch
	rm -f $(DESTDIR)$(pkgdatadir)/main/terminal/engine/_bashish_gnome-terminal_properties
	rm -f $(DESTDIR)$(pkgdatadir)/main/terminal/engine/_bashish_gnome-terminal_winch
	rm -f $(DESTDIR)$(pkgdatadir)/main/terminal/engine/_bashish_konsole_init
	rm -f $(DESTDIR)$(pkgdatadir)/main/terminal/engine/_bashish_konsole_properties
	rm -f $(DESTDIR)$(pkgdatadir)/main/terminal/engine/_bashish_linux_ansi
	rm -f $(DESTDIR)$(pkgdatadir)/main/terminal/engine/_bashish_linux_color
	rm -f $(DESTDIR)$(pkgdatadir)/main/terminal/engine/_bashish_linux_font
	rm -f $(DESTDIR)$(pkgdatadir)/main/terminal/engine/_bashish_rxvt_color
	rm -f $(DESTDIR)$(pkgdatadir)/main/terminal/engine/_bashish_rxvt_image
	rm -f $(DESTDIR)$(pkgdatadir)/main/terminal/engine/_bashish_urxvt_font
	rm -f $(DESTDIR)$(pkgdatadir)/main/terminal/engine/_bashish_vt100_posthide
	rm -f $(DESTDIR)$(pkgdatadir)/main/terminal/engine/_bashish_vt100_prehide
	rm -f $(DESTDIR)$(pkgdatadir)/main/terminal/engine/_bashish_vt100_reverse
	rm -f $(DESTDIR)$(pkgdatadir)/main/terminal/engine/_bashish_vt100_sane
	rm -f $(DESTDIR)$(pkgdatadir)/main/terminal/engine/_bashish_xterm_256
	rm -f $(DESTDIR)$(pkgdatadir)/main/terminal/engine/_bashish_xterm_ansi
	rm -f $(DESTDIR)$(pkgdatadir)/main/terminal/engine/_bashish_xterm_color
	rm -f $(DESTDIR)$(pkgdatadir)/main/terminal/engine/_bashish_xterm_font
	rm -f $(DESTDIR)$(pkgdatadir)/main/terminal/engine/_bashish_xterm_geometry
	rm -f $(DESTDIR)$(pkgdatadir)/main/terminal/engine/_bashish_xterm_printtitle
	rm -f $(DESTDIR)$(pkgdatadir)/main/terminal/engine/_bashish_xterm_winch
	rm -f $(DESTDIR)$(pkgdatadir)/main/terminal/engine/_bashish_xwsh_color
	rm -f $(DESTDIR)$(pkgdatadir)/main/terminal/init
	rm -f $(DESTDIR)$(pkgdatadir)/main/terminal/templates/gnome-terminal/schema
	rm -f $(DESTDIR)$(pkgdatadir)/overrides/prompt.sh
	rm -f $(DESTDIR)$(pkgdatadir)/overrides/theme
	rm -f $(DESTDIR)$(pkgdatadir)/themes/app/appchat/icq.png
	rm -f $(DESTDIR)$(pkgdatadir)/themes/app/appchat/smile.png
	rm -f $(DESTDIR)$(pkgdatadir)/themes/app/appchat/theme
	rm -f $(DESTDIR)$(pkgdatadir)/themes/app/appcompress/archive.png
	rm -f $(DESTDIR)$(pkgdatadir)/themes/app/appcompress/theme
	rm -f $(DESTDIR)$(pkgdatadir)/themes/app/appeditor/document.png
	rm -f $(DESTDIR)$(pkgdatadir)/themes/app/appeditor/editor.png
	rm -f $(DESTDIR)$(pkgdatadir)/themes/app/appeditor/gedit.png
	rm -f $(DESTDIR)$(pkgdatadir)/themes/app/appeditor/gnu-head.png
	rm -f $(DESTDIR)$(pkgdatadir)/themes/app/appeditor/nano.png
	rm -f $(DESTDIR)$(pkgdatadir)/themes/app/appeditor/theme
	rm -f $(DESTDIR)$(pkgdatadir)/themes/app/appeditor/vim.png
	rm -f $(DESTDIR)$(pkgdatadir)/themes/app/appeditornofont/document.png
	rm -f $(DESTDIR)$(pkgdatadir)/themes/app/appeditornofont/editor.png
	rm -f $(DESTDIR)$(pkgdatadir)/themes/app/appeditornofont/gedit.png
	rm -f $(DESTDIR)$(pkgdatadir)/themes/app/appeditornofont/gnu-head.png
	rm -f $(DESTDIR)$(pkgdatadir)/themes/app/appeditornofont/nano.png
	rm -f $(DESTDIR)$(pkgdatadir)/themes/app/appeditornofont/theme
	rm -f $(DESTDIR)$(pkgdatadir)/themes/app/appeditornofont/vim.png
	rm -f $(DESTDIR)$(pkgdatadir)/themes/app/appeditor_reversed/document.png
	rm -f $(DESTDIR)$(pkgdatadir)/themes/app/appeditor_reversed/editor.png
	rm -f $(DESTDIR)$(pkgdatadir)/themes/app/appeditor_reversed/gedit.png
	rm -f $(DESTDIR)$(pkgdatadir)/themes/app/appeditor_reversed/gnu-head.png
	rm -f $(DESTDIR)$(pkgdatadir)/themes/app/appeditor_reversed/nano.png
	rm -f $(DESTDIR)$(pkgdatadir)/themes/app/appeditor_reversed/theme
	rm -f $(DESTDIR)$(pkgdatadir)/themes/app/appeditor_reversed/vim.png
	rm -f $(DESTDIR)$(pkgdatadir)/themes/app/appevilroot/dialog-warning3.png
	rm -f $(DESTDIR)$(pkgdatadir)/themes/app/appevilroot/theme
	rm -f $(DESTDIR)$(pkgdatadir)/themes/app/appgeneric/theme
	rm -f $(DESTDIR)$(pkgdatadir)/themes/app/apphearttracker/emblem-mm.png
	rm -f $(DESTDIR)$(pkgdatadir)/themes/app/apphearttracker/emblem-sound.png
	rm -f $(DESTDIR)$(pkgdatadir)/themes/app/apphearttracker/theme
	rm -f $(DESTDIR)$(pkgdatadir)/themes/app/appinvertfgbg/theme
	rm -f $(DESTDIR)$(pkgdatadir)/themes/app/appjavac/theme
	rm -f $(DESTDIR)$(pkgdatadir)/themes/app/applatex/tex.png
	rm -f $(DESTDIR)$(pkgdatadir)/themes/app/applatex/theme
	rm -f $(DESTDIR)$(pkgdatadir)/themes/app/appmanual/book.png
	rm -f $(DESTDIR)$(pkgdatadir)/themes/app/appmanual/man.png
	rm -f $(DESTDIR)$(pkgdatadir)/themes/app/appmanual/theme
	rm -f $(DESTDIR)$(pkgdatadir)/themes/app/appmixer/mixer-48.png
	rm -f $(DESTDIR)$(pkgdatadir)/themes/app/appmixer/theme
	rm -f $(DESTDIR)$(pkgdatadir)/themes/app/appmixer/volume.png
	rm -f $(DESTDIR)$(pkgdatadir)/themes/app/appvideo/emblem-mm.png
	rm -f $(DESTDIR)$(pkgdatadir)/themes/app/appvideo/theme
	rm -f $(DESTDIR)$(pkgdatadir)/themes/ascii-art/bashish2/logo
	rm -f $(DESTDIR)$(pkgdatadir)/themes/ascii-art/bashish2/prompt.csh
	rm -f $(DESTDIR)$(pkgdatadir)/themes/ascii-art/bashish2/prompt.rc
	rm -f $(DESTDIR)$(pkgdatadir)/themes/ascii-art/bashish2/prompt.sh
	rm -f $(DESTDIR)$(pkgdatadir)/themes/ascii-art/bashish2/prompt.tcsh
	rm -f $(DESTDIR)$(pkgdatadir)/themes/ascii-art/bashish2/theme
	rm -f $(DESTDIR)$(pkgdatadir)/themes/ascii-art/bluesteel/logo
	rm -f $(DESTDIR)$(pkgdatadir)/themes/ascii-art/bluesteel/prompt.csh
	rm -f $(DESTDIR)$(pkgdatadir)/themes/ascii-art/bluesteel/prompt.rc
	rm -f $(DESTDIR)$(pkgdatadir)/themes/ascii-art/bluesteel/prompt.sh
	rm -f $(DESTDIR)$(pkgdatadir)/themes/ascii-art/bluesteel/prompt.tcsh
	rm -f $(DESTDIR)$(pkgdatadir)/themes/ascii-art/bluesteel/theme
	rm -f $(DESTDIR)$(pkgdatadir)/themes/ascii-art/box/prompt.sh
	rm -f $(DESTDIR)$(pkgdatadir)/themes/ascii-art/box/theme
	rm -f $(DESTDIR)$(pkgdatadir)/themes/ascii-art/conda/prompt.sh
	rm -f $(DESTDIR)$(pkgdatadir)/themes/ascii-art/conda/theme
	rm -f $(DESTDIR)$(pkgdatadir)/themes/ascii-art/elite/prompt.sh
	rm -f $(DESTDIR)$(pkgdatadir)/themes/ascii-art/elite/theme
	rm -f $(DESTDIR)$(pkgdatadir)/themes/ascii-art/elite2/prompt.sh
	rm -f $(DESTDIR)$(pkgdatadir)/themes/ascii-art/elite2/theme
	rm -f $(DESTDIR)$(pkgdatadir)/themes/ascii-art/fade/prompt.csh
	rm -f $(DESTDIR)$(pkgdatadir)/themes/ascii-art/fade/prompt.sh
	rm -f $(DESTDIR)$(pkgdatadir)/themes/ascii-art/fade/prompt.tcsh
	rm -f $(DESTDIR)$(pkgdatadir)/themes/ascii-art/fade/theme
	rm -f $(DESTDIR)$(pkgdatadir)/themes/ascii-art/fire/prompt.csh
	rm -f $(DESTDIR)$(pkgdatadir)/themes/ascii-art/fire/prompt.dos
	rm -f $(DESTDIR)$(pkgdatadir)/themes/ascii-art/fire/prompt.fish
	rm -f $(DESTDIR)$(pkgdatadir)/themes/ascii-art/fire/prompt.rc
	rm -f $(DESTDIR)$(pkgdatadir)/themes/ascii-art/fire/prompt.sh
	rm -f $(DESTDIR)$(pkgdatadir)/themes/ascii-art/fire/prompt.tcsh
	rm -f $(DESTDIR)$(pkgdatadir)/themes/ascii-art/fire/theme
	rm -f $(DESTDIR)$(pkgdatadir)/themes/ascii-art/flowerpower/prompt.sh
	rm -f $(DESTDIR)$(pkgdatadir)/themes/ascii-art/flowerpower/theme
	rm -f $(DESTDIR)$(pkgdatadir)/themes/ascii-art/m0an/prompt.bash
	rm -f $(DESTDIR)$(pkgdatadir)/themes/ascii-art/m0an/prompt.tcsh
	rm -f $(DESTDIR)$(pkgdatadir)/themes/ascii-art/m0an/theme
	rm -f $(DESTDIR)$(pkgdatadir)/themes/ascii-art/m0an/uglyascii
	rm -f $(DESTDIR)$(pkgdatadir)/themes/ascii-art/m0an/uglyascii.UTF-8
	rm -f $(DESTDIR)$(pkgdatadir)/themes/ascii-art/m0an/utglyascii.UTF-8
	rm -f $(DESTDIR)$(pkgdatadir)/themes/ascii-art/moo/prompt.bash
	rm -f $(DESTDIR)$(pkgdatadir)/themes/ascii-art/moo/theme
	rm -f $(DESTDIR)$(pkgdatadir)/themes/ascii-art/poker/ambience.xpm
	rm -f $(DESTDIR)$(pkgdatadir)/themes/ascii-art/poker/prompt.bash
	rm -f $(DESTDIR)$(pkgdatadir)/themes/ascii-art/poker/theme
	rm -f $(DESTDIR)$(pkgdatadir)/themes/ascii-art/spiffydeb/prompt.sh
	rm -f $(DESTDIR)$(pkgdatadir)/themes/ascii-art/spiffydeb/theme
	rm -f $(DESTDIR)$(pkgdatadir)/themes/ascii-art/spiffyred/prompt.sh
	rm -f $(DESTDIR)$(pkgdatadir)/themes/ascii-art/spiffyred/theme
	rm -f $(DESTDIR)$(pkgdatadir)/themes/ascii-art/uberprompt/prompt.sh
	rm -f $(DESTDIR)$(pkgdatadir)/themes/ascii-art/uberprompt/theme
	rm -f $(DESTDIR)$(pkgdatadir)/themes/ascii-art/urbandawn/prompt.bash
	rm -f $(DESTDIR)$(pkgdatadir)/themes/ascii-art/urbandawn/theme
	rm -f $(DESTDIR)$(pkgdatadir)/themes/computer/appleiie/appleiie
	rm -f $(DESTDIR)$(pkgdatadir)/themes/computer/appleiie/prompt.bash
	rm -f $(DESTDIR)$(pkgdatadir)/themes/computer/appleiie/theme
	rm -f $(DESTDIR)$(pkgdatadir)/themes/computer/commodore/amiga/prompt.bash
	rm -f $(DESTDIR)$(pkgdatadir)/themes/computer/commodore/amiga/shell.png
	rm -f $(DESTDIR)$(pkgdatadir)/themes/computer/commodore/amiga/theme
	rm -f $(DESTDIR)$(pkgdatadir)/themes/computer/commodore/amigados/amiga.png
	rm -f $(DESTDIR)$(pkgdatadir)/themes/computer/commodore/amigados/logo.guru
	rm -f $(DESTDIR)$(pkgdatadir)/themes/computer/commodore/amigados/logo.start
	rm -f $(DESTDIR)$(pkgdatadir)/themes/computer/commodore/amigados/prompt.bash
	rm -f $(DESTDIR)$(pkgdatadir)/themes/computer/commodore/amigados/shell.png
	rm -f $(DESTDIR)$(pkgdatadir)/themes/computer/commodore/amigados/theme
	rm -f $(DESTDIR)$(pkgdatadir)/themes/computer/commodore/c128/boot
	rm -f $(DESTDIR)$(pkgdatadir)/themes/computer/commodore/c128/commodore.png
	rm -f $(DESTDIR)$(pkgdatadir)/themes/computer/commodore/c128/prompt.bash
	rm -f $(DESTDIR)$(pkgdatadir)/themes/computer/commodore/c128/prompt.csh
	rm -f $(DESTDIR)$(pkgdatadir)/themes/computer/commodore/c128/prompt.fish
	rm -f $(DESTDIR)$(pkgdatadir)/themes/computer/commodore/c128/prompt.rc
	rm -f $(DESTDIR)$(pkgdatadir)/themes/computer/commodore/c128/prompt.tcsh
	rm -f $(DESTDIR)$(pkgdatadir)/themes/computer/commodore/c128/theme
	rm -f $(DESTDIR)$(pkgdatadir)/themes/computer/commodore/c64/boot
	rm -f $(DESTDIR)$(pkgdatadir)/themes/computer/commodore/c64/commodore.png
	rm -f $(DESTDIR)$(pkgdatadir)/themes/computer/commodore/c64/prompt.bash
	rm -f $(DESTDIR)$(pkgdatadir)/themes/computer/commodore/c64/prompt.csh
	rm -f $(DESTDIR)$(pkgdatadir)/themes/computer/commodore/c64/prompt.fish
	rm -f $(DESTDIR)$(pkgdatadir)/themes/computer/commodore/c64/prompt.rc
	rm -f $(DESTDIR)$(pkgdatadir)/themes/computer/commodore/c64/prompt.tcsh
	rm -f $(DESTDIR)$(pkgdatadir)/themes/computer/commodore/c64/theme
	rm -f $(DESTDIR)$(pkgdatadir)/themes/computer/commodore/cbmii/boot
	rm -f $(DESTDIR)$(pkgdatadir)/themes/computer/commodore/cbmii/prompt.bash
	rm -f $(DESTDIR)$(pkgdatadir)/themes/computer/commodore/cbmii/theme
	rm -f $(DESTDIR)$(pkgdatadir)/themes/computer/commodore/pet/boot
	rm -f $(DESTDIR)$(pkgdatadir)/themes/computer/commodore/pet/prompt.bash
	rm -f $(DESTDIR)$(pkgdatadir)/themes/computer/commodore/pet/theme
	rm -f $(DESTDIR)$(pkgdatadir)/themes/computer/commodore/vic20/boot.32k
	rm -f $(DESTDIR)$(pkgdatadir)/themes/computer/commodore/vic20/boot.5k
	rm -f $(DESTDIR)$(pkgdatadir)/themes/computer/commodore/vic20/commodore.png
	rm -f $(DESTDIR)$(pkgdatadir)/themes/computer/commodore/vic20/prompt.bash
	rm -f $(DESTDIR)$(pkgdatadir)/themes/computer/commodore/vic20/prompt.csh
	rm -f $(DESTDIR)$(pkgdatadir)/themes/computer/commodore/vic20/prompt.fish
	rm -f $(DESTDIR)$(pkgdatadir)/themes/computer/commodore/vic20/prompt.rc
	rm -f $(DESTDIR)$(pkgdatadir)/themes/computer/commodore/vic20/prompt.tcsh
	rm -f $(DESTDIR)$(pkgdatadir)/themes/computer/commodore/vic20/theme
	rm -f $(DESTDIR)$(pkgdatadir)/themes/computer/commodore/vic20/vic20
	rm -f $(DESTDIR)$(pkgdatadir)/themes/computer/commodore/vic20/vic20_startup_screen.gif
	rm -f $(DESTDIR)$(pkgdatadir)/themes/computer/dos/3270pclogo
	rm -f $(DESTDIR)$(pkgdatadir)/themes/computer/dos/8striper
	rm -f $(DESTDIR)$(pkgdatadir)/themes/computer/dos/doscopyright
	rm -f $(DESTDIR)$(pkgdatadir)/themes/computer/dos/msadvlogo
	rm -f $(DESTDIR)$(pkgdatadir)/themes/computer/dos/prompt.csh
	rm -f $(DESTDIR)$(pkgdatadir)/themes/computer/dos/prompt.dos
	rm -f $(DESTDIR)$(pkgdatadir)/themes/computer/dos/prompt.fish
	rm -f $(DESTDIR)$(pkgdatadir)/themes/computer/dos/prompt.ksh
	rm -f $(DESTDIR)$(pkgdatadir)/themes/computer/dos/prompt.rc
	rm -f $(DESTDIR)$(pkgdatadir)/themes/computer/dos/prompt.sh
	rm -f $(DESTDIR)$(pkgdatadir)/themes/computer/dos/prompt.tcsh
	rm -f $(DESTDIR)$(pkgdatadir)/themes/computer/dos/theme
	rm -f $(DESTDIR)$(pkgdatadir)/themes/computer/lcars/lcars-2.jpg
	rm -f $(DESTDIR)$(pkgdatadir)/themes/computer/lcars/prompt.csh
	rm -f $(DESTDIR)$(pkgdatadir)/themes/computer/lcars/prompt.sh
	rm -f $(DESTDIR)$(pkgdatadir)/themes/computer/lcars/prompt.tcsh
	rm -f $(DESTDIR)$(pkgdatadir)/themes/computer/lcars/theme
	rm -f $(DESTDIR)$(pkgdatadir)/themes/computer/multics/boot
	rm -f $(DESTDIR)$(pkgdatadir)/themes/computer/multics/multics
	rm -f $(DESTDIR)$(pkgdatadir)/themes/computer/multics/prompt.bash
	rm -f $(DESTDIR)$(pkgdatadir)/themes/computer/multics/theme
	rm -f $(DESTDIR)$(pkgdatadir)/themes/computer/mvs/boot
	rm -f $(DESTDIR)$(pkgdatadir)/themes/computer/mvs/prompt.bash
	rm -f $(DESTDIR)$(pkgdatadir)/themes/computer/mvs/theme
	rm -f $(DESTDIR)$(pkgdatadir)/themes/computer/mvsmono/boot
	rm -f $(DESTDIR)$(pkgdatadir)/themes/computer/mvsmono/prompt.bash
	rm -f $(DESTDIR)$(pkgdatadir)/themes/computer/mvsmono/theme
	rm -f $(DESTDIR)$(pkgdatadir)/themes/computer/oric1/boot
	rm -f $(DESTDIR)$(pkgdatadir)/themes/computer/oric1/commodore.png
	rm -f $(DESTDIR)$(pkgdatadir)/themes/computer/oric1/prompt.bash
	rm -f $(DESTDIR)$(pkgdatadir)/themes/computer/oric1/prompt.csh
	rm -f $(DESTDIR)$(pkgdatadir)/themes/computer/oric1/prompt.fish
	rm -f $(DESTDIR)$(pkgdatadir)/themes/computer/oric1/prompt.rc
	rm -f $(DESTDIR)$(pkgdatadir)/themes/computer/oric1/prompt.tcsh
	rm -f $(DESTDIR)$(pkgdatadir)/themes/computer/oric1/theme
	rm -f $(DESTDIR)$(pkgdatadir)/themes/computer/ubuntu/prompt.bash
	rm -f $(DESTDIR)$(pkgdatadir)/themes/computer/ubuntu/prompt.tcsh
	rm -f $(DESTDIR)$(pkgdatadir)/themes/computer/ubuntu/theme
	rm -r $(DESTDIR)$(pkgdatadir)/themes/computer/ubuntu
	rm -r $(DESTDIR)$(pkgdatadir)/themes/computer/oric1
	rm -r $(DESTDIR)$(pkgdatadir)/themes/computer/mvsmono
	rm -r $(DESTDIR)$(pkgdatadir)/themes/computer/mvs
	rm -r $(DESTDIR)$(pkgdatadir)/themes/computer/multics
	rm -r $(DESTDIR)$(pkgdatadir)/themes/computer/lcars
	rm -r $(DESTDIR)$(pkgdatadir)/themes/computer/dos
	rm -r $(DESTDIR)$(pkgdatadir)/themes/computer/commodore/vic20
	rm -r $(DESTDIR)$(pkgdatadir)/themes/computer/commodore/pet
	rm -r $(DESTDIR)$(pkgdatadir)/themes/computer/commodore/cbmii
	rm -r $(DESTDIR)$(pkgdatadir)/themes/computer/commodore/c64
	rm -r $(DESTDIR)$(pkgdatadir)/themes/computer/commodore/c128
	rm -r $(DESTDIR)$(pkgdatadir)/themes/computer/commodore/amigados
	rm -r $(DESTDIR)$(pkgdatadir)/themes/computer/commodore/amiga
	rm -r $(DESTDIR)$(pkgdatadir)/themes/computer/commodore
	rm -r $(DESTDIR)$(pkgdatadir)/themes/computer/appleiie
	rm -r $(DESTDIR)$(pkgdatadir)/themes/computer
	rm -r $(DESTDIR)$(pkgdatadir)/themes/ascii-art/urbandawn
	rm -r $(DESTDIR)$(pkgdatadir)/themes/ascii-art/uberprompt
	rm -r $(DESTDIR)$(pkgdatadir)/themes/ascii-art/spiffyred
	rm -r $(DESTDIR)$(pkgdatadir)/themes/ascii-art/spiffydeb
	rm -r $(DESTDIR)$(pkgdatadir)/themes/ascii-art/poker
	rm -r $(DESTDIR)$(pkgdatadir)/themes/ascii-art/moo
	rm -r $(DESTDIR)$(pkgdatadir)/themes/ascii-art/m0an
	rm -r $(DESTDIR)$(pkgdatadir)/themes/ascii-art/flowerpower
	rm -r $(DESTDIR)$(pkgdatadir)/themes/ascii-art/fire
	rm -r $(DESTDIR)$(pkgdatadir)/themes/ascii-art/fade
	rm -r $(DESTDIR)$(pkgdatadir)/themes/ascii-art/elite2
	rm -r $(DESTDIR)$(pkgdatadir)/themes/ascii-art/elite
	rm -r $(DESTDIR)$(pkgdatadir)/themes/ascii-art/conda
	rm -r $(DESTDIR)$(pkgdatadir)/themes/ascii-art/box
	rm -r $(DESTDIR)$(pkgdatadir)/themes/ascii-art/bluesteel
	rm -r $(DESTDIR)$(pkgdatadir)/themes/ascii-art/bashish2
	rm -r $(DESTDIR)$(pkgdatadir)/themes/ascii-art
	rm -r $(DESTDIR)$(pkgdatadir)/themes/app/appvideo
	rm -r $(DESTDIR)$(pkgdatadir)/themes/app/appmixer
	rm -r $(DESTDIR)$(pkgdatadir)/themes/app/appmanual
	rm -r $(DESTDIR)$(pkgdatadir)/themes/app/applatex
	rm -r $(DESTDIR)$(pkgdatadir)/themes/app/appjavac
	rm -r $(DESTDIR)$(pkgdatadir)/themes/app/appinvertfgbg
	rm -r $(DESTDIR)$(pkgdatadir)/themes/app/apphearttracker
	rm -r $(DESTDIR)$(pkgdatadir)/themes/app/appgeneric
	rm -r $(DESTDIR)$(pkgdatadir)/themes/app/appevilroot
	rm -r $(DESTDIR)$(pkgdatadir)/themes/app/appeditor_reversed
	rm -r $(DESTDIR)$(pkgdatadir)/themes/app/appeditornofont
	rm -r $(DESTDIR)$(pkgdatadir)/themes/app/appeditor
	rm -r $(DESTDIR)$(pkgdatadir)/themes/app/appcompress
	rm -r $(DESTDIR)$(pkgdatadir)/themes/app/appchat
	rm -r $(DESTDIR)$(pkgdatadir)/themes/app
	rm -r $(DESTDIR)$(pkgdatadir)/themes
	rm -r $(DESTDIR)$(pkgdatadir)/overrides
	rm -r $(DESTDIR)$(pkgdatadir)/main/terminal/templates/gnome-terminal
	rm -r $(DESTDIR)$(pkgdatadir)/main/terminal/templates
	rm -r $(DESTDIR)$(pkgdatadir)/main/terminal/engine
	rm -r $(DESTDIR)$(pkgdatadir)/main/terminal
	rm -r $(DESTDIR)$(pkgdatadir)/main/prompt/sh
	rm -r $(DESTDIR)$(pkgdatadir)/main/prompt/rc/sys
	rm -r $(DESTDIR)$(pkgdatadir)/main/prompt/rc
	rm -r $(DESTDIR)$(pkgdatadir)/main/prompt/osh
	rm -r $(DESTDIR)$(pkgdatadir)/main/prompt/fish/sys
	rm -r $(DESTDIR)$(pkgdatadir)/main/prompt/fish
	rm -r $(DESTDIR)$(pkgdatadir)/main/prompt/dos/sys
	rm -r $(DESTDIR)$(pkgdatadir)/main/prompt/dos
	rm -r $(DESTDIR)$(pkgdatadir)/main/prompt/csh/sys
	rm -r $(DESTDIR)$(pkgdatadir)/main/prompt/csh
	rm -r $(DESTDIR)$(pkgdatadir)/main/prompt
	rm -r $(DESTDIR)$(pkgdatadir)/main/bashish/sys
	rm -r $(DESTDIR)$(pkgdatadir)/main/bashish
	rm -r $(DESTDIR)$(pkgdatadir)/main
	rm -r $(DESTDIR)$(pkgdatadir)/lib
	rm -r $(DESTDIR)$(pkgdatadir)/defaults
	rm -r $(DESTDIR)$(pkgdatadir)
